In [4]:
import numpy as np
import array as arr
a = numpy.array([[ 0,  1,  2,  3],
               [ 0,  5,  6,  7],
               [ 0,  9, 10, 11],
               [0, 13, 14, 15]])

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 0,  9, 10, 11],
       [ 0, 13, 14, 15]])

In [6]:
a= np.delete(a,np.where(~a.any(axis=0))[0], axis=1)

In [7]:
a

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [41]:
numpy.delete(a, numpy.s_[:-3], axis=1) 

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])