In [40]:
import pandas as pd
import os
import cv2
import numpy as np

In [41]:
data = pd.read_csv('training-b.csv')

In [42]:
data[:10]

original filename  scanid  digit  num database name original  \
0   Scan_17_digit_1_num_3.png      17      1    3                 DUISRT   
1  Scan_112_digit_1_num_0.png     112      1    0                 DUISRT   
2   Scan_81_digit_5_num_8.png      81      5    8                 DUISRT   
3    Scan_5_digit_7_num_1.png       5      7    1                 DUISRT   
4    Scan_5_digit_0_num_6.png       5      0    6                 DUISRT   
5   Scan_44_digit_1_num_1.png      44      1    1                 DUISRT   
6   Scan_18_digit_0_num_7.png      18      0    7                 DUISRT   
7   Scan_61_digit_0_num_1.png      61      0    1                 DUISRT   
8   Scan_54_digit_3_num_2.png      54      3    2                 DUISRT   
9   Scan_58_digit_7_num_6.png      58      7    6                 DUISRT   

  database name    filename  
0    training-d  d00000.png  
1    training-d  d00001.png  
2    training-d  d00002.png  
3    training-d  d00003.png  
4    training-d  d00004.png  
5    training-d  d00005.png  
6    training-d  d00006.png  
7    training-d  d00007.png  
8    training-d  d00008.png  
9    training-d  d00009.png

In [43]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [44]:
names = data.iloc[:, 0].values
digits = data.iloc[:, 3].values

In [45]:
names[:10]

array(['d00000.png', 'd00001.png', 'd00002.png', 'd00003.png',
       'd00004.png', 'd00005.png', 'd00006.png', 'd00007.png',
       'd00008.png', 'd00009.png'], dtype=object)

In [46]:
print(type(names))

<class 'numpy.ndarray'>


In [47]:
digits[:10]

array([3, 0, 8, 1, 6, 1, 7, 1, 2, 6], dtype=int64)

In [48]:
len(names)

10908

In [49]:
len(digits)

10908

In [50]:
x = []
y = []

In [51]:
for i in range(0, len(names)):
    img = cv2.imread('./training-b/'+names[i],0)
    img = cv2.resize(img,(32,32))
    x.append(img)
    y.append(digits[i])
    
    #print(img.shape)
    #print(digits[i])
    #print(i,'done')

In [55]:
a = x[2]

In [56]:
cv2.imshow('image', a)
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

In [57]:
type(x)

list

In [58]:
type(y)

list

In [59]:
x[:5]

[array([[244, 243, 244, ..., 243, 240, 246],
        [242, 243, 244, ..., 244, 245, 242],
        [244, 240, 244, ..., 243, 242, 245],
        ...,
        [239, 236, 241, ..., 241, 238, 240],
        [239, 238, 239, ..., 239, 238, 241],
        [238, 240, 239, ..., 242, 240, 241]], dtype=uint8),
 array([[240, 243, 242, ..., 244, 240, 241],
        [241, 243, 241, ..., 243, 245, 245],
        [241, 242, 240, ..., 244, 241, 243],
        ...,
        [240, 241, 238, ..., 238, 241, 243],
        [240, 239, 241, ..., 243, 242, 242],
        [242, 242, 239, ..., 245, 246, 243]], dtype=uint8),
 array([[236, 237, 238, ..., 239, 237, 239],
        [239, 239, 236, ..., 237, 241, 239],
        [236, 237, 240, ..., 241, 243, 241],
        ...,
        [233, 230, 233, ..., 239, 240, 239],
        [235, 235, 236, ..., 235, 242, 240],
        [229, 234, 232, ..., 241, 238, 237]], dtype=uint8),
 array([[241, 238, 243, ..., 243, 244, 244],
        [244, 241, 241, ..., 245, 240, 243],
        [242, 24

In [60]:
x= np.array(x)

In [61]:
type(x)

numpy.ndarray

In [62]:
y[:10]

[3, 0, 8, 1, 6, 1, 7, 1, 2, 6]

In [63]:
type(y)

list

In [64]:
y= np.array(y)

In [65]:
y[:10]

array([3, 0, 8, 1, 6, 1, 7, 1, 2, 6], dtype=int64)

In [66]:
np.save('training-b_Numta_x.npy', x)
np.save('training-d_Numta_y.npy', y)